# Generated by Django 3.1 on 2020-08-17 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_remove_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('date_page', models.DateTimeField(auto_now_add=True, null=True)),
                ('content', models.TextField(null=True)),
                ('mood', models.CharField(choices=[('Delighted', 'Delighted'), ('Excited', 'Excited'), ('Neutral', 'Neutral'), ('Speechless', 'Speechless'), ('Happy', 'Happy'), ('Flirty', 'Flirty'), ('Sad', 'Sad'), ('Guilty', 'Guilty'), ('Broken', 'Broken'), ('Shitty', 'Shitty'), ('Furious', 'Furious'), ('Nervous', 'Nervous')], max_length=50, null=True)),
                ('user', models.ForeignKey(default='Test', null=True, on_delete=django.db.models.deletion.SET_NULL, to='diary.user')),
            ],
        ),
        migrations.DeleteModel(
            name='DairyPage',
        ),
    ]
