# Generated by Django 3.1 on 2020-08-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DairyPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('date_page', models.DateTimeField(auto_now_add=True, null=True)),
                ('content', models.TextField(null=True)),
                ('mood', models.CharField(choices=[('Delighted', 'Delighted'), ('Excited', 'Excited'), ('Neutral', 'Neutral'), ('Speechless', 'Speechless'), ('Happy', 'Happy'), ('Flirty', 'Flirty'), ('Sad', 'Sad'), ('Guilty', 'Guilty'), ('Broken', 'Broken'), ('Shitty', 'Shitty'), ('Furious', 'Furious'), ('Nervous', 'Nervous')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
