# Generated by Django 3.1 on 2020-08-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20200829_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarypage',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='userclient',
            old_name='client',
            new_name='user',
        ),
    ]
