# Generated by Django 3.1 on 2020-09-01 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0008_auto_20200829_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarypage',
            name='customer',
        ),
        migrations.AddField(
            model_name='diarypage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
