# Generated by Django 3.1 on 2020-09-01 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarypage',
            old_name='user',
            new_name='customer',
        ),
    ]
